### ISSUE TITLE
.net core 2.1 is not support for Client.GetStreamAsync() method

### ISSUE THREAD

**Issue by JeffreySu** [StephenClearyExamples/AsyncDynamicZip#1]
https://github.com/StephenClearyExamples/AsyncDynamicZip/blob/c12aa3a54b057092d05e0efcd8a49af6cb882a25/Example/WebApplication/Controllers/FileController.cs#L36

.net core 2.1 is not support for Microsoft.AspNetCore.Sockets.Client.GetStreamAsync() method, do you have a version to support .net core?

Thanks!

**Comment by JeffreySu** [comment]
@StephenCleary

**Comment by StephenCleary** [comment]
According to [this](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.getstreamasync?view=netframework-4.7.2#applies-to) it's supported. I would be very surprised if `HttpClient.GetStreamAsync` was removed.

There *have* been other changes in 2.0 that require slightly different usage; see [here](https://blog.stephencleary.com/2016/11/streaming-zip-on-aspnet-core.html#comment-3570035602) for details.

**Comment by JeffreySu** [comment]
It's working, thank you!
